services:
  fluentbit:
    image: "cr.fluentbit.io/fluent/fluent-bit:2.0"
    container_name: fluentbit
    restart: unless-stopped
    volumes:
      - "./config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf"
      - "./config/parsers.conf:/fluent-bit/etc/parsers.conf"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/log:/var/log:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "24224:24224"
      - "514:514/tcp"
    environment:
      - TZ=Asia/Kuwait
    command:
      - "-c"
      - "/fluent-bit/etc/fluent-bit.conf"
    depends_on:
      - loki
  loki:
    image: "grafana/loki:latest"
    command: "-config.file=/etc/loki/local-config.yaml"
    volumes:
      - "loki-data:/loki"
      - "./config/loki.yaml:/etc/loki/local-config.yaml:ro"
    expose:
      - "3100"
  grafana:
    image: "grafana/grafana:latest"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
    expose:
      - "3000"
    volumes:
      - "grafana-data:/var/lib/grafana"
    depends_on:
      - loki
volumes:
  loki-data: null
  grafana-data: null
