service:
  flush: 1
  daemon: off
  log_level: debug
  # parsers_file: /fluent-bit/etc/parsers.conf

pipeline:
  inputs:
    - name: syslog
      mode: udp
      port: 514
      listen: 0.0.0.0
      tag: synology
      parser: synology_syslog

    # - name: tail
    #   path: /var/lib/docker/containers/*/*.log
    #   # parser: docker
    #   tag: docker.*

  # filters:
  #   - name: parser
  #     match: "synology*"
  #     parser: banana

  outputs:
    - name: loki
      match: "*"
      host: loki
      port: 3100
      labels: job=fluentbit

    # - name: stdout
    #   match: "*"
    #   format: json_lines
