service:
  flush: 1
  daemon: off
  # log_level: debug
  # parsers_file: /fluent-bit/etc/parsers.conf

pipeline:
  inputs:
    - name: syslog
      tag: synology
      mode: udp
      port: 514
      listen: 0.0.0.0
      parser: synology_syslog

    - name: tail
      tag: docker.*
      path: /var/lib/docker/containers/*/*.log
      # parser: docker

  # filters:
  #   - name: parser
  #     match: "synology*"
  #     parser: banana

  outputs:
    - name: loki
      match: "*"
      host: loki
      port: 3100
      labels: job=$tag

    # - name: stdout
    #   match: "*"
    #   format: json_lines
